### ISSUE TITLE
Readme should explain `consumerkeyandsecret` better.

### ISSUE THREAD

**Issue by amandabee** [owenst/geotweets#1]
It would be sweet if this was more clear: 

> The program requires a file in this folder called consumerkeyandsecret
> which contains only a consumer key on the first line and consumer
> secret (the longer one) on the second line. You can get this by
> creating an app under your twitter account online.

Should probably say something more like ...

> The program looks for a file named  `consumerkeyandsecret` which should contain your 
> consumer key on the first line and consumer secret (the longer one) on the second line. 
> Get a key and secret by visiting https://apps.twitter.com/ and creating a new app.

**Comment by owenst** [comment]
Thanks for the suggestion @amandabee ! I clarified this in the README while having someone go through the process. 
Commit: https://github.com/owenst/geotweets/commit/28398dc056ecaa74d3f3b1c2624745bab354bdff
